### ISSUE TITLE
How to filter multiple file extensions?

### ISSUE THREAD

**Issue by dacsi** [nbsp-team/MaterialFilePicker#31] opened 2016-07-12 14:50 UTC
Great tool, but I would like to know if it is possible to filter 2 or more file types. For example in my app I want the user to be able to pick only mp3 files, so i used this line

`.withFilter(Pattern.compile(".*\\.mp3$"))`

But now what if i wanted the user to be able to choose also .ogg file? How could I achieve that?

**Comment by dimorinny** [comment] 2016-07-12 14:53
Duplicate of issue #22

**Closed by dimorinny** 2016-07-12 14:53 UTC
Labels: duplicate
